### ISSUE TITLE
Chat name is not updated

### ISSUE THREAD

**Issue by vkaverin** [vsevolodk/birthday.bot#1]
Опытным путём выяснили, что новые чаты создаются с именем по-умолчанию (имена участников). Должно же быть хотя бы имя именинника и дата рождения.

**Comment by vskaiman** [comment]
Проблема в классе BirthdayChatCreator. Когда бот пытается создать чат, используя контакты у которых нет бота в списке контактов, падает ошибка, и создаётся в итоге пустой чат без остальной логики. Нужно добавить обработку такой ситуации.
