### ISSUE TITLE
Chat bot leaves chat after BDay is over

### ISSUE THREAD

**Issue by vkaverin** [vsevolodk/birthday.bot#3]
При вызове \bdone бот просто выходит из чата.
Надо сделать так, чтобы он как-то маркировал день рождения как завершившийся, например с обозначением подаренного подарка (на будущее) или что-то подобное.

**Comment by vskaiman** [comment]
Идея крута, после реализации https://github.com/vsevolodk/birthday.bot/issues/16, надо добавить команду которая выводит списком подарки за предыдущие года.

**Comment by vskaiman** [comment]
Now bot have command for adding history of gifts by year
